### ISSUE TITLE
If the Deck restarts while replay recording enabled, it causes "too early" errors when trying to save.

### ISSUE THREAD

**Issue by Kerobotto** [safijari/decky-recorder-fork#6]
This can be manually fixed by switching replay off and on again after the restart. While in this error state, the buttons are greyed out. 

![image](https://github.com/safijari/decky-recorder-fork/assets/131631094/5957639d-fd9a-42cf-9297-de9a6748dd72)
[Logs.zip](https://github.com/safijari/decky-recorder-fork/files/12488695/Logs.zip)

**Comment by Valom** [comment]
having the same error with the same temporary solution.

**Comment by cinqrouge** [comment]
same problem and solution, I'm looking at the code but i'm in way over my head lol.

it seams to get stuck on around line 336 in main.py since there are no last clip equation it checks is alway smaller than 2 ( and return a 0 to the saveRollingRecording method on line 44 in index.tsx ? am really not sure about this one )

`        if time.time() - self._last_clip_time < 2:
            logger.info("Too early to record another clip")
            return 0
`

Thanks for your time, sorry if this is not the proper way to share my "findings"

Have a nice day :)

**Comment by safijari** [comment]
It's more than likely happening because some necessary service isn't present when the plugin first initializes and it goes into a bad state. Can probably be fixed by watching for the recording process and restarting it if it seems to have failed.

**Comment by safijari** [comment]
It's fixed now in my latest commits. Will try to get this released soon.

**Comment by cinqrouge** [comment]
oh cool! thanks you so much to have taken the time :). I'll take a look at the commit and see if I can learn anything.
